export const ADD_MERCHANT = 'ADD_MERCHANT';
export const DELETE_MERCHANT = 'DELETE_MERCHANT';
export const EDIT_MERCHANT = 'EDIT_MERCHANT';
export const SELECT_MERCHANT = 'SELECT_MERCHANT';
export const MODIFY_BIDS = "MODIFY_BIDS";
export const EDIT_MERCHANT_SUBMIT = "EDIT_MERCHANT_SUBMIT";
export const SORT_BIDS = "SORT_BIDS";
